console.log('hello world');
console.log(207410274);
console.log(true);
var greeting='LIUHUAIWEN';
console.log(greeting);
console.log([2019,02,19]);
console.log({firstname:'懷文',lastname:'劉'});
console.table({firstname:'懷文',lastname:'劉'});
console.error('This is some error');
console.warn('This is some warning');
console.time('Hello');
  console.log('Hello World');
  console.log('Hello World');
  console.log('Hello World');
  console.log('Hello World');
  console.log('Hello World');
  console.log('Hello World');
  console.log('Hello World');
console.timeEnd('Hello');
//console.clear();